"""
seed_demo_data.py

Populates the Tutor and Student Dashboards with THREE separate courses
(so the dashboard grid actually looks like a real, in-use system rather
than one lonely card), each with 1-2 topics and a real AI-generated
question, plus several student submissions of varying quality across
different courses for a meaningful progress trend.

IMPORTANT: the questions and feedback are generated by calling your
REAL ai_service.py functions (generate_question / generate_feedback) —
the same functions your live Flask routes call. Nothing here is
fabricated; each run makes real requests to whichever provider is set
as ACTIVE_MODEL in your .env, so what ends up on screen is genuine
system output, not a mock-up.

Safe to re-run: it looks up courses/topics/questions by name first and
reuses them instead of duplicating. Each run adds fresh submissions on
top of whatever already exists.

Run from inside the 'backend' folder:
    python seed_demo_data.py
"""

import sys

from app import create_app
from extensions import db
from models import (
    User, Course, SyllabusTopic, Question, Submission, Feedback, Enrollment,
)
from services.ai_service import (
    generate_question, generate_feedback,
    ACTIVE_MODEL, ANTHROPIC_MODEL, DEEPSEEK_MODEL, OPENAI_MODEL,
)
from services.code_quality_scorer import score_code_quality

TUTOR_EMAIL = None    # None = auto-pick the first real tutor account found
STUDENT_EMAIL = None  # None = auto-pick the first real student account found

GOLD_STANDARD_TUTOR_EMAIL = "gold-standard@nexicode.local"
MODEL_IDS = {"claude": ANTHROPIC_MODEL, "gpt": OPENAI_MODEL, "deepseek": DEEPSEEK_MODEL}

# Three separate courses, so the dashboard grid actually fills up like a
# real multi-module tutor account, instead of one card in an empty grid.
DEMO_COURSES = [
    {
        "title": "Introduction to JavaScript",
        "module_code": "CIS101-DEMO",
        "topics": [
            {
                "title": "Variables and Data Types",
                "outcomes": "Students will be able to declare variables using let/const and assign values of different types (string, number, boolean).",
                "rubric": "1-10. Correct let/const use (3), correct value types (3), console.log all values (2), clean code (2).",
                "difficulty": "easy",
            },
            {
                "title": "Loops — for loop",
                "outcomes": "Students will be able to write a for loop that iterates a specific number of times and performs an action each iteration.",
                "rubric": "1-10. Correct loop syntax (4), correct iteration count (3), correct output (3).",
                "difficulty": "easy",
            },
        ],
    },
    {
        "title": "Web Development Fundamentals",
        "module_code": "WEB201-DEMO",
        "topics": [
            {
                "title": "Functions and Return Values",
                "outcomes": "Students will be able to define a function that accepts parameters and returns a computed value.",
                "rubric": "1-10. Correct function declaration (3), correct parameter use (3), correct return value (4).",
                "difficulty": "medium",
            },
            {
                "title": "Arrays",
                "outcomes": "Students will be able to create an array, add/access elements by index, and iterate over its contents.",
                "rubric": "1-10. Correct array creation (3), correct indexing (3), correct iteration (4).",
                "difficulty": "hard",
            },
        ],
    },
    {
        "title": "Advanced Programming Concepts",
        "module_code": "PROG301-DEMO",
        "topics": [
            {
                "title": "Error Handling — try/catch",
                "outcomes": "Students will be able to wrap risky code in a try/catch block and handle the resulting error gracefully.",
                "rubric": "1-10. Correct try/catch structure (4), meaningful error handling (3), correct output (3).",
                "difficulty": "medium",
            },
        ],
    },
]

# (course index, topic index within that course, code, note) — spread
# across different courses so the student's Progress tab and course
# list both look genuinely in-use rather than single-item.
DEMO_SUBMISSIONS = [
    (0, 0, 'let name = "Alex"\nlet age = 21;\nconsole.log(name);\n', "incomplete: missing semicolon, only prints one variable"),
    (0, 1, 'for (let i = 0; i < 5; i++) {\n  console.log(i);\n}\n', "correct, clean solution"),
    (1, 0, 'function add(a, b) {\n  console.log(a + b)\n}\n', "logic error: console.logs instead of returning"),
    (2, 0, 'try {\n  riskyCall();\n} catch (e) {\n  console.log("Error: " + e.message);\n}\n', "correct, clean solution"),
]


def find_account(role, exact_email):
    if exact_email:
        user = User.query.filter_by(email=exact_email).first()
        if not user:
            print(f"ERROR: no user found with email {exact_email}")
            sys.exit(1)
        return user
    user = (
        User.query
        .filter(User.role == role, User.email != GOLD_STANDARD_TUTOR_EMAIL)
        .order_by(User.created_at.asc())
        .first()
    )
    if not user:
        print(f"ERROR: no {role} account exists yet — create one through the app first.")
        sys.exit(1)
    return user


def get_or_create_course(tutor, course_spec):
    course = Course.query.filter_by(module_code=course_spec["module_code"]).first()
    if course:
        print(f"Reusing existing course '{course.title}' ({course.module_code}).")
        return course
    course = Course(title=course_spec["title"], module_code=course_spec["module_code"], tutor_id=tutor.id)
    db.session.add(course)
    db.session.flush()
    print(f"Created course '{course.title}' ({course.module_code}).")
    return course


def get_or_create_topic(course, spec):
    topic = SyllabusTopic.query.filter_by(course_id=course.id, topic_title=spec["title"]).first()
    if topic:
        print(f"  Reusing existing topic '{topic.topic_title}'.")
        return topic
    topic = SyllabusTopic(
        course_id=course.id,
        topic_title=spec["title"],
        learning_outcomes=spec["outcomes"],
        marking_rubric=spec["rubric"],
    )
    db.session.add(topic)
    db.session.flush()
    print(f"  Created topic '{topic.topic_title}'.")
    return topic


def get_or_create_question(topic, difficulty):
    question = Question.query.filter_by(topic_id=topic.id).first()
    if question:
        print(f"  Reusing existing question for '{topic.topic_title}'.")
        return question
    print(f"  Calling generate_question() for '{topic.topic_title}' (real API call, please wait)...")
    question_text = generate_question(
        topic_title=topic.topic_title,
        learning_outcomes=topic.learning_outcomes,
        marking_rubric=topic.marking_rubric,
        difficulty=difficulty,
    )
    question = Question(
        topic_id=topic.id,
        question_text=question_text,
        difficulty=difficulty,
        ai_model_used=MODEL_IDS.get(ACTIVE_MODEL, ACTIVE_MODEL),
    )
    db.session.add(question)
    db.session.flush()
    print(f"    -> {question_text[:100]}...")
    return question


def main():
    app = create_app()
    with app.app_context():
        tutor = find_account("tutor", TUTOR_EMAIL)
        student = find_account("student", STUDENT_EMAIL)
        print(f"Using tutor:   {tutor.name} <{tutor.email}>")
        print(f"Using student: {student.name} <{student.email}>\n")

        courses = []
        for course_spec in DEMO_COURSES:
            course = get_or_create_course(tutor, course_spec)
            topics_and_questions = []
            for topic_spec in course_spec["topics"]:
                topic = get_or_create_topic(course, topic_spec)
                question = get_or_create_question(topic, topic_spec["difficulty"])
                topics_and_questions.append((topic, question))
            courses.append((course, topics_and_questions))

            if not Enrollment.query.filter_by(student_id=student.id, course_id=course.id).first():
                db.session.add(Enrollment(student_id=student.id, course_id=course.id))
                db.session.flush()

        print(f"\nSubmitting {len(DEMO_SUBMISSIONS)} answers across different courses...")
        for course_index, topic_index, code, note in DEMO_SUBMISSIONS:
            _, topics_and_questions = courses[course_index]
            topic, question = topics_and_questions[topic_index]
            print(f"  Submitting to '{topic.topic_title}' ({note}) — calling generate_feedback()...")

            submission = Submission(student_id=student.id, question_id=question.id, code_submitted=code)
            db.session.add(submission)
            db.session.flush()

            fb_result = generate_feedback(
                question_text=question.question_text,
                code_submitted=code,
                learning_outcomes=topic.learning_outcomes,
                marking_rubric=topic.marking_rubric,
            )
            submission.score = fb_result["score"]
            db.session.add(Feedback(
                submission_id=submission.id,
                feedback_text=fb_result["feedback_text"],
                feedback_type="guided",
                ai_model_used=fb_result["model"],
            ))
            quality_result = score_code_quality(code)
            print(f"    -> score {fb_result['score']}/10, quality {quality_result}")

        db.session.commit()

        print("\n" + "=" * 70)
        print(f"DONE — {len(DEMO_COURSES)} courses now exist, with",
              sum(len(c['topics']) for c in DEMO_COURSES), "topics/questions and",
              len(DEMO_SUBMISSIONS), "submissions across them.")
        print("=" * 70)
        print("Refresh your browser — tutor sees 3 courses in the grid;")
        print("student sees 3 joined courses and a progress trend across all of them.")


if __name__ == "__main__":
    main()