"""
test_claude.py

A quick, standalone test to confirm your Claude API key is working.
Run this from inside your 'backend' folder:

    python test_claude.py

If it's working, you'll see a real, unique question generated by Claude.
If something's wrong, it'll tell you exactly what to check.
"""

import os
from dotenv import load_dotenv

load_dotenv()

print("Checking your .env file...")

key = os.getenv("ANTHROPIC_API_KEY", "")

if not key:
    print("❌ ANTHROPIC_API_KEY is empty or missing in your .env file.")
    print("   Open .env and make sure the line looks like:")
    print("   ANTHROPIC_API_KEY=sk-ant-api03-xxxxxxxxxxxx")
    exit()

if not key.startswith("sk-ant-"):
    print("⚠️  Your key doesn't start with 'sk-ant-' — double check you")
    print("   copied the whole key correctly from console.anthropic.com")

print(f"✅ Found a key starting with: {key[:12]}...")
print("Sending a real request to Claude... (this costs a tiny fraction of a cent)\n")

try:
    from services.ai_service import generate_question

    result = generate_question(
        topic_title="Loops and Iteration",
        learning_outcomes="Students should be able to use for and while loops correctly.",
        marking_rubric="Correct loop logic (50%); correct termination (30%); style (20%).",
        difficulty="medium",
        model="claude",
    )

    print("=" * 60)
    print("CLAUDE RESPONDED WITH A REAL GENERATED QUESTION:")
    print("=" * 60)
    print(result)
    print("=" * 60)
    print("\n✅ SUCCESS — your Claude API key is working correctly.")
    print("   If you run this again, you should get a DIFFERENT question")
    print("   each time (proving it's really Claude, not the old mock text).")

except Exception as e:
    print("❌ Something went wrong when calling Claude:")
    print(f"   {e}")
    print("\nCommon causes:")
    print("  - No billing credit added yet in console.anthropic.com")
    print("  - Key copied incorrectly (extra space, missing characters)")
    print("  - You're not running this from inside the 'backend' folder")